-- 1 
SELECT NAME FROM SONGS;
-- 2
SELECT NAME FROM SONGS ORDER BY TEMPO;
-- 3
SELECT NAME FROM SONGS ORDER BY DURATION_MS DESC LIMIT 5;
-- 4
SELECT NAME FROM SONGS WHERE ENERGY > 0.75 AND DANCEABILITY > 0.75 AND VALENCE > 0.75;
-- 5
SELECT AVG(ENERGY) FROM SONGS;
-- 6
SELECT SONGS.NAME FROM SONGS JOIN ARTISTS ON SONGS.ARTIST_ID = ARTISTS.ID WHERE ARTISTS.NAME = 'Post Malone';
-- 7
SELECT AVG(SONGS.ENERGY) FROM SONGS JOIN ARTISTS ON SONGS.ARTIST_ID = ARTISTS.ID WHERE ARTISTS.NAME = 'Drake';
-- 8
SELECT NAME FROM SONGS WHERE INSTR(NAME, 'feat.') != 0;
